Load in NumPy


In [1]:
import numpy as np

The Basics

In [15]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
b = np.array([[1,2,4,5,2],[6,7,2,6,3.2]])
print(b)

[[1.  2.  4.  5.  2. ]
 [6.  7.  2.  6.  3.2]]


In [8]:
#Get dimesion
a.ndim

1

In [9]:
#get shape (rows and the coulmns)
b.shape

(2, 5)

In [12]:
#get type
a.dtype

dtype('int16')

In [16]:
#get size
a.itemsize

4

In [18]:
#get total size
a.nbytes

12

Accessing changing specific elements, rows coulmns,etc

In [19]:
a = np.array([[1,2,3,5,6,4,3,2],[2,4,1,6,3,1,4,3,]])
print(a)

[[1 2 3 5 6 4 3 2]
 [2 4 1 6 3 1 4 3]]


In [21]:
#get a specific element[r,c]
a[1,-2]

4

In [22]:
# get a specific  row
a[0, :]

array([1, 2, 3, 5, 6, 4, 3, 2])

In [23]:
#get a specific coulmn
a[:,2]

array([3, 1])

In [24]:
#getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 5, 4])

In [25]:
a[1,5] =20
print(a)

[[ 1  2  3  5  6  4  3  2]
 [ 2  4  1  6  3 20  4  3]]


In [26]:
a[:,2]=5
print(a)

[[ 1  2  5  5  6  4  3  2]
 [ 2  4  5  6  3 20  4  3]]


In [27]:
a[:,2]=a[1,3]
print(a)

[[ 1  2  6  5  6  4  3  2]
 [ 2  4  6  6  3 20  4  3]]


*3d examle

In [ ]:
b = np.array([[1,2,3],[4,4,5],[3,6,4]])